"""Names of the 70 keypoints SAM 3D Body predicts (MHR70 layout)."""

NOSE = 0
LEFT_SHOULDER, RIGHT_SHOULDER = 5, 6
LEFT_ELBOW, RIGHT_ELBOW = 7, 8
LEFT_HIP, RIGHT_HIP = 9, 10
LEFT_KNEE, RIGHT_KNEE = 11, 12
LEFT_ANKLE, RIGHT_ANKLE = 13, 14
LEFT_BIG_TOE, LEFT_SMALL_TOE, LEFT_HEEL = 15, 16, 17
RIGHT_BIG_TOE, RIGHT_SMALL_TOE, RIGHT_HEEL = 18, 19, 20
RIGHT_WRIST, LEFT_WRIST = 41, 62
NECK = 69

LEFT_FOOT = (LEFT_BIG_TOE, LEFT_SMALL_TOE, LEFT_HEEL)
RIGHT_FOOT = (RIGHT_BIG_TOE, RIGHT_SMALL_TOE, RIGHT_HEEL)
FEET = LEFT_FOOT + RIGHT_FOOT

# Bones drawn by the viewer's skeleton overlay (keypoint index pairs).
BONES = (
    (LEFT_ANKLE, LEFT_KNEE), (LEFT_KNEE, LEFT_HIP), (RIGHT_ANKLE, RIGHT_KNEE), (RIGHT_KNEE, RIGHT_HIP),
    (LEFT_HIP, RIGHT_HIP), (LEFT_SHOULDER, LEFT_HIP), (RIGHT_SHOULDER, RIGHT_HIP),
    (LEFT_SHOULDER, RIGHT_SHOULDER), (LEFT_SHOULDER, LEFT_ELBOW), (RIGHT_SHOULDER, RIGHT_ELBOW),
    (LEFT_ELBOW, LEFT_WRIST), (RIGHT_ELBOW, RIGHT_WRIST), (NECK, NOSE),
    (LEFT_ANKLE, LEFT_HEEL), (LEFT_ANKLE, LEFT_BIG_TOE), (RIGHT_ANKLE, RIGHT_HEEL), (RIGHT_ANKLE, RIGHT_BIG_TOE),
)  # fmt: skip
